services:
  postgres-db:
    image: postgres:16-alpine
    container_name: meu-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=aulafull
    volumes:
      - postgres-data-local:/var/lib/postgresql/data

  api-spring:
    container_name: eduplataform-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/aulafull
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_SECRETKEY=awjidauwdaaid87231dcahbsurnasxvcb34d
      - SPRING_EMISSOR=ajdawijd416ll
      - SPRING_TEMPOEXPIRACAO=30
      - SPRING_MAIL_HOST=sandbox.smtp.mailtrap.io
      - SPRING_MAIL_PORT=2525
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME:-fake}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD:-fake}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

      - APP_EMAIL_REMETENTE=${APP_EMAIL_REMETENTE:-no-reply@eduplatform.com}
    depends_on:
      - postgres-db

volumes:
  postgres-data-local: