spring.application.name=ApiEduPlataformSenac

spring.datasource.url=jdbc:postgresql://localhost:5432/eduplatform
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.secretKey=awjidauwdaaid87231dcahbsurnasxvcb34d
spring.emissor=ajdawijd416ll
spring.tempoExpiracao=30

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d31dfa795029ac
spring.mail.password=255b99aa063ca0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.email.remetente=no-reply@eduplatform.com